import { StyleSheet } from 'react-native';
import { COLORS } from './colors';

export const commonStyles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: COLORS.darkBg,
    padding: 16,
  },
  listScreen: {
    flex: 1,
    backgroundColor: COLORS.white,
    padding: 16,
  },
  title: {
    fontSize: 28,
    fontWeight: '700',
    color: COLORS.white,
    marginBottom: 24,
  },
  subtitle: {
    fontSize: 20,
    fontWeight: '600',
    color: COLORS.white,
  },
  infoText: {
    fontSize: 16,
    color: COLORS.white,
    marginBottom: 12,
  },
  input: {
    width: '100%',
    maxWidth: 260,
    borderWidth: 1,
    borderColor: COLORS.white,
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 8,
    color: COLORS.white,
  },
  button: {
    backgroundColor: COLORS.primaryBlue,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    minWidth: 180,
    marginVertical: 6,
    alignItems: 'center',
  },
  buttonText: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: '600',
  },
  listItem: {
    borderWidth: 1,
    borderColor: COLORS.white,
    borderRadius: 8,
    padding: 12,
    marginTop: 10,
  },
  listItemTitle: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: '600',
  },
  listItemSub: {
    color: COLORS.white,
    fontSize: 13,
    marginTop: 4,
  },
  // Top info bar
  topBar: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    backgroundColor: COLORS.primaryBlue,
  },
  topBarText: {
    color: COLORS.white,
    fontSize: 14,
  },
  // Map container
  mapContainer: {
    flex: 1,
    marginHorizontal: 16,
    marginVertical: 8,
    borderRadius: 8,
  },
  // Bottom navigation
  bottomNav: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    alignItems: 'center',
    backgroundColor: COLORS.primaryBlue,
    paddingVertical: 12,
    paddingHorizontal: 8,
    paddingBottom: 20,
  },
  navButton: {
    alignItems: 'center',
    paddingVertical: 8,
    paddingHorizontal: 16,
  },
  navButtonText: {
    color: COLORS.white,
    fontSize: 12,
    marginTop: 4,
  },
  // SOS Button - Centered and Larger
  sosContainer: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 90,
    alignItems: 'center',
    justifyContent: 'center',
  },
  sosButtonLarge: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: COLORS.red,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: COLORS.black,
    shadowColor: COLORS.black,
    shadowOffset: { width: 3, height: 3 },
    shadowOpacity: 0.5,
    shadowRadius: 3,
  },
  sosButtonTextLarge: {
    color: COLORS.white,
    fontSize: 20,
    fontWeight: '700',
    marginTop: 4,
  },
  // Add Point Button
  addPointButton: {
    position: 'absolute',
    right: 20,
    top: 80,
    width: 50,
    height: 50,
    borderRadius: 25,
    backgroundColor: COLORS.primaryBlue,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: COLORS.black,
    shadowColor: COLORS.black,
    shadowOffset: { width: 2, height: 2 },
    shadowOpacity: 0.5,
    shadowRadius: 2,
  },
  // Add Point Menu
  addPointMenu: {
    position: 'absolute',
    right: 20,
    top: 140,
    backgroundColor: COLORS.primaryBlue,
    borderRadius: 8,
    padding: 8,
    minWidth: 200,
    borderWidth: 2,
    borderColor: COLORS.black,
  },
  menuTitle: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: '600',
    marginBottom: 8,
    textAlign: 'center',
  },
  menuOption: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 10,
    paddingHorizontal: 12,
    backgroundColor: COLORS.primaryBlue,
    borderRadius: 6,
    marginBottom: 4,
  },
  menuOptionText: {
    color: COLORS.white,
    fontSize: 14,
    marginLeft: 10,
  },
  // Section styles
  sectionContainer: {
    paddingHorizontal: 16,
    paddingVertical: 8,
  },
  sectionTitle: {
    color: COLORS.white,
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 8,
  },
});
